name: clean-playlist-2

services:
  clean-playlist-backend:
    image: ghcr.io/sfn-git/clean-playlist-2-backend:main
    ports:
      - 8080:8080
    environment:
      - SPOTIFY_CLIENT_ID=
      - SPOTIFY_CLIENT_SECRET=
      - APP_BASE_URL=
      - APP_BASE_DOMAIN=
      - FRONTEND_URL=
      - ENV=prod #set as dev or prod
  clean-playlist-frontend:
    image: ghcr.io/sfn-git/clean-playlist-2-frontend:main
    ports:
      - 8081:8080
    environment:
      - VITE_API_URL=